Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 2);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 2);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 2);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 13);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 13);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 13);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 14);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 14);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 14);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 16);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 16);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 16);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 17);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 17);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 17);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 18);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 18);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 18);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 20);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 20);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 20);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 22);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 22);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 22);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 23);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 23);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 23);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 26);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 26);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 26);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 29);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 29);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 29);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 32);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 32);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 32);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 36);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 36);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 36);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 37);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 37);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 37);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 39);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 39);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 39);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 40);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 40);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 40);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 45);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 45);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 45);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (1, 46);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (2, 46);
Insert into SIIG_MTD_R_FORMULA_ELAB
   (ID_ELABORAZIONE, ID_FORMULA)
 Values
   (3, 46);
COMMIT;
