INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (0,0);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (8,8);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (15,15);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (25,25);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (30,30);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (32,32);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (35,35);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (40,40);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (42,42);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (45,45);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (48,48);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (51,51);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (52,52);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (55,55);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (58,58);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (60,60);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (65,65);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (70,70);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (75,75);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (80,80);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (81,81);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (88,88);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (90,90);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (93,93);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (95,95);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (96,96);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (100,100);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (109,109);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (110,110);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (112,112);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (125,125);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (127,127);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (130,130);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (131,131);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (132,132);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (138,138);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (140,140);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (145,145);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (148,148);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (150,150);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (160,160);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (180,180);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (210,210);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (230,230);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (250,250);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (339,339);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (420,420);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (467,467);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (500,500);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (567,567);
INSERT INTO siig_d_distanza (id_distanza,distanza) VALUES (780,780);
commit;

INSERT INTO siig_d_gravita (id_gravita, descrizione) VALUES (1,'ELEVATA LETALITA');
INSERT INTO siig_d_gravita (id_gravita, descrizione) VALUES (2,'INIZIO LETALITA');
INSERT INTO siig_d_gravita (id_gravita, descrizione) VALUES (3,'LESIONI IRREVERSIBILI');
INSERT INTO siig_d_gravita (id_gravita, descrizione) VALUES (4,'LESIONI REVERSIBILI');
INSERT INTO siig_d_gravita (id_gravita, descrizione) VALUES (5,'UNICA GRAVITA');
commit;